language: csharp
solution: CICD_Test.sln

matrix:
  include:
    - os: linux
      dist: focal
      dotnet: 7.0.100
      mono: none

# Add more platforms as needed

install:
  - dotnet restore

script:
  - dotnet build
  - dotnet test
